### ISSUE TITLE
Auction sort - add Critical attack value

### ISSUE THREAD

**Issue by lpachecob** [DinoDevs/GladiatusCrazyAddon#225]
in the auction we need an item that orders for critical damage

**Comment by FrutyX** [comment]
No need to script this now, just a note for future Gram :D.

So I was thinking that this should be easy, because it is already done, you just add this one, it's not. The problem was that it's always in an tooltip, but then I saw https://github.com/DinoDevs/GladiatusCrazyAddon/commit/7b3fdc6f45af8aaa06531d5b5eee44b5847f26c5 and it could work similarly.

**Comment by GreatApo** [comment]
All item stats with numerical values (eg +10) will now be automatically included in the sorting options. If a stat doesn't appear, it is probably because it is not available in the displayed items.

**Comment by FrutyX** [comment]
@GreatApo 

auction.js?4.3.5&built=1640302859860:564 Uncaught DOMException: Failed to set a named property on 'DOMStringMap': 'item_kritické-léčení' is not a valid property name.
    at Number.<anonymous> (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640302859860:564:44)
    at Function.each (https://s34-cz.gladiatus.gameforge.com/game/9401/js/jquery.js:3:3064)
    at HTMLTableCellElement.<anonymous> (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640302859860:563:12)
    at Function.each (https://s34-cz.gladiatus.gameforge.com/game/9401/js/jquery.js:3:3006)
    at m.fn.init.each (https://s34-cz.gladiatus.gameforge.com/game/9401/js/jquery.js:3:837)
    at Object.parseItems (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640302859860:559:42)
    at Object.init (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640302859860:457:9)
    at Object.inject (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640302859860:32:20)
    at fireLoad (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640302859860:856:15)

**Comment by FrutyX** [comment]
![Výstřižek](https://user-images.githubusercontent.com/23278552/147300820-cfe723d7-8bd3-474f-8720-6dfdb6f37f99.PNG)

Auctions right now:

![explosion-boom](https://user-images.githubusercontent.com/23278552/147300828-d6445525-42e7-4508-affa-7f49b92527ac.gif)

**Comment by GreatApo** [comment]
> kritické-léčení

It is because of the cz characters. I am trying to find a way to replace them... it works with Greek XD

**Comment by FrutyX** [comment]
That may be a problem, what about Chinese? Russian? Turkish? Persian? And some others, can't you apply some encoding on it? For my language, utf-8 is usually the best way (and well, most used), but you probably know that.

**Comment by GreatApo** [comment]
> That may be a problem, what about Chinese? Russian? Turkish? Persian? And some others, can't you apply some encoding on it? For my language, utf-8 is usually the best way (and well, most used), but you probably know that.

Yeah, that is what I am after but nothing I have tried yet works...

**Comment by GreatApo** [comment]
@FrutyX give me some feedback. It should work now.

**Comment by FrutyX** [comment]
@GreatApo Damn, this one is gonna be problematic:

```
auction.js?4.3.5&built=1640333754594:564 Uncaught DOMException: Failed to set a named property on 'DOMStringMap': 'item_kritickC3A9-lC3A9C48DenC3AD' is not a valid property name.
    at Number.<anonymous> (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640333754594:564:44)
    at Function.each (https://s34-cz.gladiatus.gameforge.com/game/9401/js/jquery.js:3:3064)
    at HTMLTableCellElement.<anonymous> (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640333754594:563:12)
    at Function.each (https://s34-cz.gladiatus.gameforge.com/game/9401/js/jquery.js:3:3006)
    at m.fn.init.each (https://s34-cz.gladiatus.gameforge.com/game/9401/js/jquery.js:3:837)
    at Object.parseItems (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640333754594:559:42)
    at Object.init (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640333754594:457:9)
    at Object.inject (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640333754594:32:20)
    at fireLoad (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640333754594:857:15)
```

**Comment by FrutyX** [comment]
RIP Auctions, had to revert back so I can use them

![apo](https://user-images.githubusercontent.com/23278552/147340169-39017e3c-4375-443b-a972-206adae5a622.gif)

**Comment by GreatApo** [comment]
> @GreatApo Damn, this one is gonna be problematic:
> 
> ```
> auction.js?4.3.5&built=1640333754594:564 Uncaught DOMException: Failed to set a named property on 'DOMStringMap': 'item_kritickC3A9-lC3A9C48DenC3AD' is not a valid property name.
>     at Number.<anonymous> (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640333754594:564:44)
>     at Function.each (https://s34-cz.gladiatus.gameforge.com/game/9401/js/jquery.js:3:3064)
>     at HTMLTableCellElement.<anonymous> (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640333754594:563:12)
>     at Function.each (https://s34-cz.gladiatus.gameforge.com/game/9401/js/jquery.js:3:3006)
>     at m.fn.init.each (https://s34-cz.gladiatus.gameforge.com/game/9401/js/jquery.js:3:837)
>     at Object.parseItems (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640333754594:559:42)
>     at Object.init (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640333754594:457:9)
>     at Object.inject (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640333754594:32:20)
>     at fireLoad (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640333754594:857:15)
> ```

Wtf is its problem? 😂😂😂😂

**Comment by FrutyX** [comment]
Round 2:

```
auction.js?4.3.5&built=1640361483219:564 Uncaught DOMException: Failed to set a named property on 'DOMStringMap': 'data-item_zdrav%-e-d' is not a valid attribute name.
    at Number.<anonymous> (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640361483219:564:44)
    at Function.each (https://s34-cz.gladiatus.gameforge.com/game/9401/js/jquery.js:3:3064)
    at HTMLTableCellElement.<anonymous> (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640361483219:563:12)
    at Function.each (https://s34-cz.gladiatus.gameforge.com/game/9401/js/jquery.js:3:3006)
    at m.fn.init.each (https://s34-cz.gladiatus.gameforge.com/game/9401/js/jquery.js:3:837)
    at Object.parseItems (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640361483219:559:42)
    at Object.init (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640361483219:457:9)
    at Object.inject (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640361483219:32:20)
    at fireLoad (chrome-extension://hkbmmenmpniffngmkigofhgbflhhokka/core/source/auction.js?4.3.5&built=1640361483219:857:15)
```

I think this one stands for life/health and in Czech it's just "zdraví".

**Comment by GreatApo** [comment]
@FrutyX are you sure you are running the last commit? I am replacing all % so there shouldn't be one in the name "data-item_zdrav%-e-d"

**Comment by FrutyX** [comment]
Okay, again, now.

I've re-downloaded the whole source folder, replaced it, went on another account, cleared all GCA data and checked the auctions, I got the same errors as above.

Sorry Apo.

**Comment by FrutyX** [comment]
Either that or 

`Uncaught DOMException: Failed to set a named property on 'DOMStringMap': 'data-item_kritick%-f-d-%-f-atok' is not a valid attribute name.` keeps kicking in.

**Comment by FrutyX** [comment]
I went to check the Arabic version, and what the hell, it even works in Arabic, diacritics in my language are really tearing it apart I see.

**Comment by GreatApo** [comment]
@FrutyX round 3...

**Comment by FrutyX** [comment]
Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaand we have a winner! Noice!

![tested](https://user-images.githubusercontent.com/23278552/147372966-e6681c96-b743-42ee-a62e-d5469000fa35.PNG)
